prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select (count(distinct ?p) as ?num_of_property) where {
#select distinct ?p where {
  { ?s ?p ?o . }
  union
  { ?p rdfs:domain ?c }
  union
  { ?p rdfs:range ?c }
  union
  { ?p rdfs:subPropertyOf ?x }
  union
  { ?x rdfs:subPropertyOf ?p }

  filter( !strstarts(str(?p), "http://www.w3.org/1999/02/22-rdf-syntax-ns#") &&
          !strstarts(str(?p), "http://www.w3.org/2000/01/rdf-schema#") &&
          !strstarts(str(?p), "http://www.w3.org/2002/07/owl#") )
}
